/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmQLTV;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Docgia;
import model.DocgiaDao;

/**
 *
 * @author My PC
 */
public class frmDOCGIA extends javax.swing.JFrame {

    /**
     * Creates new form frmMENU
     */
    List<Docgia> list = new ArrayList<>();
    private int currentindex;
    private String hinhanh = "";
    private int role;
    private String manv;

    public frmDOCGIA() {
        initComponents();
        rdbMDG.setSelected(true);
        this.setSize(970, 540);
        lblBR.setIcon(new ImageIcon(getClass().getResource("/BR/brdg-2.jpg")));
        setLocationRelativeTo(null);
        laydulieuDocgia("");
    }

    // set vai trò quản lý
    public void setRole(int role) {
        this.role = role;
        checkRole(role);
    }
// set mã nhân vên

    public void setManv(String manv) {
        this.manv = manv;
    }
// kiểm tra vai trò : 1 - Quản lý , 2 - Nhân viên

    public void checkRole(int role) {
        if (role == 1) {
            mitNHANVIEN.hide();
            mitTHONGKE.hide();
        }
    }

    private void laydulieuDocgia(String sql) {
        try {
            list.clear();
            tblDOCGIA.removeAll();
            list = DocgiaDao.laydulieuDocgia(sql);
            fillToTableNhanvien();
            laydulieuDG();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }

    private void fillToTableNhanvien() {
        DefaultTableModel model = (DefaultTableModel) tblDOCGIA.getModel();
        model.setRowCount(0);
        for (Docgia dg : list) {
            Object[] row = new Object[]{dg.getMadg(), dg.getTendg(), dg.getSdt(), dg.getDiachi(), dg.getMk(), dg.getHinhanh()};
            model.addRow(row);
        }
    }

    private void laydulieuDG() {
        try {
            if (list.size() == 1) {
                currentindex = 0;
            }
            Docgia dg = list.get(currentindex);
            txtMADG.setText(dg.getMadg());
            txtTENDG.setText(dg.getTendg());
            txtDGSDT.setText(dg.getSdt());
            txtDGDIACHI.setText(dg.getDiachi());
            txtDGMATKHAU.setText(dg.getMk());
            btnDGHINH.setIcon(new ImageIcon(getClass().getResource("/IMGDG/" + dg.getHinhanh())));
            this.hinhanh = dg.getHinhanh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy độc giả");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDANGXUAT = new javax.swing.JButton();
        btnSACH = new javax.swing.JButton();
        btnPHIEUNHAP = new javax.swing.JButton();
        btnPHIEUMUON = new javax.swing.JButton();
        btnPHIEUMUONCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        DOCGIA = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnDGHINH = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDOCGIA = new javax.swing.JTable();
        txtMADG = new javax.swing.JTextField();
        txtTENDG = new javax.swing.JTextField();
        txtDGSDT = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnDGSEACH = new javax.swing.JButton();
        rdbMDG = new javax.swing.JRadioButton();
        rdbTENDG = new javax.swing.JRadioButton();
        rdbSDT = new javax.swing.JRadioButton();
        txtSEACH = new javax.swing.JTextField();
        btnDGNHAPMOI = new javax.swing.JButton();
        btnDGTHEMMOI = new javax.swing.JButton();
        btnDGCAPNHAT = new javax.swing.JButton();
        btnDGXOA = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        txtDGMATKHAU = new javax.swing.JTextField();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtDGDIACHI = new javax.swing.JTextArea();
        lblBR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDANGXUAT = new javax.swing.JMenuItem();
        mitDOIMK = new javax.swing.JMenuItem();
        mitTHOAT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitNHANVIEN = new javax.swing.JMenuItem();
        mitDOCGIA = new javax.swing.JMenuItem();
        mitSACH = new javax.swing.JMenuItem();
        mitTACGIA = new javax.swing.JMenuItem();
        mitNXB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitPHIEUNHAP = new javax.swing.JMenuItem();
        mitPHIEUMUON = new javax.swing.JMenuItem();
        mitPHIEUMUONCT = new javax.swing.JMenuItem();
        mitPHIEUPHAT = new javax.swing.JMenuItem();
        mitTHONGKE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHDSD = new javax.swing.JMenuItem();
        mitTTPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        btnDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        btnDANGXUAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        btnDANGXUAT.setText("Đăng xuất");
        btnDANGXUAT.setFocusable(false);
        btnDANGXUAT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDANGXUAT.setMaximumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setMinimumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setPreferredSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGXUATActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDANGXUAT);

        btnSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        btnSACH.setText("Sách");
        btnSACH.setFocusable(false);
        btnSACH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSACH.setMaximumSize(new java.awt.Dimension(91, 51));
        btnSACH.setMinimumSize(new java.awt.Dimension(91, 51));
        btnSACH.setPreferredSize(new java.awt.Dimension(91, 51));
        btnSACH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSACHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSACH);

        btnPHIEUNHAP.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        btnPHIEUNHAP.setText("Phiếu nhập");
        btnPHIEUNHAP.setFocusable(false);
        btnPHIEUNHAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUNHAP.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUNHAPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUNHAP);

        btnPHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        btnPHIEUMUON.setText("Phiếu mượn");
        btnPHIEUMUON.setFocusable(false);
        btnPHIEUMUON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUON.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUON);

        btnPHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUONCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        btnPHIEUMUONCT.setText("Phiếu mượn CT");
        btnPHIEUMUONCT.setFocusable(false);
        btnPHIEUMUONCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUONCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUONCT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        DOCGIA.setBackground(new java.awt.Color(255, 255, 255));
        DOCGIA.setOpaque(false);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 255));
        jLabel21.setText("Mã độc giả");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 255));
        jLabel22.setText("Tên độc giả");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 255));
        jLabel23.setText("Địa chỉ");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("Số điện thoại");

        btnDGHINH.setBackground(new java.awt.Color(255, 255, 255));
        btnDGHINH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGHINHActionPerformed(evt);
            }
        });

        tblDOCGIA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã độc giả", "Tên độc giả", "Số điện thoại", "Địa chỉ", "Mật khẩu", "Hình ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDOCGIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDOCGIAMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDOCGIA);
        if (tblDOCGIA.getColumnModel().getColumnCount() > 0) {
            tblDOCGIA.getColumnModel().getColumn(3).setResizable(false);
        }

        txtMADG.setEnabled(false);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel6.setOpaque(false);

        btnDGSEACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDGSEACH.setForeground(new java.awt.Color(51, 51, 51));
        btnDGSEACH.setText("SEACH");
        btnDGSEACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGSEACHActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbMDG);
        rdbMDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMDG.setForeground(new java.awt.Color(0, 0, 255));
        rdbMDG.setText("Mã độc giả");

        buttonGroup1.add(rdbTENDG);
        rdbTENDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbTENDG.setForeground(new java.awt.Color(0, 0, 255));
        rdbTENDG.setText("Tên độc giả");

        buttonGroup1.add(rdbSDT);
        rdbSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbSDT.setForeground(new java.awt.Color(0, 0, 255));
        rdbSDT.setText("SĐT");

        txtSEACH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbMDG)
                            .addComponent(rdbTENDG)
                            .addComponent(rdbSDT)
                            .addComponent(txtSEACH, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnDGSEACH)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(txtSEACH, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbMDG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbTENDG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDGSEACH))
        );

        btnDGNHAPMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDGNHAPMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnDGNHAPMOI.setText("Nhập mới");
        btnDGNHAPMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGNHAPMOIActionPerformed(evt);
            }
        });

        btnDGTHEMMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDGTHEMMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnDGTHEMMOI.setText("Thêm mới");
        btnDGTHEMMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGTHEMMOIActionPerformed(evt);
            }
        });

        btnDGCAPNHAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDGCAPNHAT.setForeground(new java.awt.Color(51, 51, 51));
        btnDGCAPNHAT.setText("Cập nhật");
        btnDGCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGCAPNHATActionPerformed(evt);
            }
        });

        btnDGXOA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDGXOA.setForeground(new java.awt.Color(51, 51, 51));
        btnDGXOA.setText("Xóa");
        btnDGXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDGXOAActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 255));
        jLabel49.setText("Mật khẩu");

        txtDGDIACHI.setColumns(20);
        txtDGDIACHI.setRows(5);
        jScrollPane10.setViewportView(txtDGDIACHI);

        javax.swing.GroupLayout DOCGIALayout = new javax.swing.GroupLayout(DOCGIA);
        DOCGIA.setLayout(DOCGIALayout);
        DOCGIALayout.setHorizontalGroup(
            DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DOCGIALayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4)
                    .addGroup(DOCGIALayout.createSequentialGroup()
                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DOCGIALayout.createSequentialGroup()
                                .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DOCGIALayout.createSequentialGroup()
                                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel22)
                                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(23, 23, 23)
                                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMADG, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTENDG, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                                            .addComponent(txtDGMATKHAU)))
                                    .addGroup(DOCGIALayout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(btnDGNHAPMOI)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnDGTHEMMOI)))
                                .addGap(35, 35, 35)
                                .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DOCGIALayout.createSequentialGroup()
                                        .addComponent(btnDGCAPNHAT)
                                        .addGap(36, 36, 36)
                                        .addComponent(btnDGXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(DOCGIALayout.createSequentialGroup()
                                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23))
                                        .addGap(18, 18, 18)
                                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDGSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnDGHINH, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1549, Short.MAX_VALUE))
        );
        DOCGIALayout.setVerticalGroup(
            DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DOCGIALayout.createSequentialGroup()
                .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DOCGIALayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel24)
                            .addComponent(txtMADG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDGSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DOCGIALayout.createSequentialGroup()
                                .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtTENDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel49)
                                    .addComponent(txtDGMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DOCGIALayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDGNHAPMOI)
                            .addComponent(btnDGTHEMMOI)
                            .addComponent(btnDGCAPNHAT)
                            .addComponent(btnDGXOA)))
                    .addGroup(DOCGIALayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDGHINH, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        lblBR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBR.setName(""); // NOI18N
        lblBR.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DOCGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblBR, javax.swing.GroupLayout.PREFERRED_SIZE, 2496, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DOCGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblBR, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Hệ thống");

        mitDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        mitDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        mitDANGXUAT.setText("Đăng xuất");
        mitDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDANGXUATActionPerformed(evt);
            }
        });
        jMenu1.add(mitDANGXUAT);

        mitDOIMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondmk.jpg"))); // NOI18N
        mitDOIMK.setText("Đổi mật khẩu");
        mitDOIMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOIMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDOIMK);

        mitTHOAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconexit1.jpg"))); // NOI18N
        mitTHOAT.setText("Thoát");
        mitTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHOATActionPerformed(evt);
            }
        });
        jMenu1.add(mitTHOAT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mitNHANVIEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnv1.jpg"))); // NOI18N
        mitNHANVIEN.setText("Nhân viên");
        mitNHANVIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNHANVIENActionPerformed(evt);
            }
        });
        jMenu2.add(mitNHANVIEN);

        mitDOCGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondocgia1.jpg"))); // NOI18N
        mitDOCGIA.setText("Độc giả");
        mitDOCGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOCGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitDOCGIA);

        mitSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        mitSACH.setText("Sách");
        mitSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSACHActionPerformed(evt);
            }
        });
        jMenu2.add(mitSACH);

        mitTACGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icontacgia1.jpg"))); // NOI18N
        mitTACGIA.setText("Tác giả");
        mitTACGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTACGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitTACGIA);

        mitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnxb1.jpg"))); // NOI18N
        mitNXB.setText("Nhà xuất bản");
        mitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNXBActionPerformed(evt);
            }
        });
        jMenu2.add(mitNXB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mitPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        mitPHIEUNHAP.setText("Phiếu nhập sách");
        mitPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUNHAPActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUNHAP);

        mitPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        mitPHIEUMUON.setText("Phiếu mượn sách");
        mitPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUON);

        mitPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        mitPHIEUMUONCT.setText("Phiếu mượn sách chi tiết");
        mitPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONCTActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUONCT);

        mitPHIEUPHAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconpp.png"))); // NOI18N
        mitPHIEUPHAT.setText("Phiếu phạt");
        mitPHIEUPHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUPHATActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUPHAT);

        mitTHONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbdtk.jpg"))); // NOI18N
        mitTHONGKE.setText("Thống kê số liệu");
        mitTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHONGKEActionPerformed(evt);
            }
        });
        jMenu3.add(mitTHONGKE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mitHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconhdsd1.jpg"))); // NOI18N
        mitHDSD.setText("Hướng dẫn sử dụng");
        mitHDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHDSDActionPerformed(evt);
            }
        });
        jMenu4.add(mitHDSD);

        mitTTPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/gt_1.png"))); // NOI18N
        mitTTPB.setText("Thông tin phiên bản");
        mitTTPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTTPBActionPerformed(evt);
            }
        });
        jMenu4.add(mitTTPB);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_mitDANGXUATActionPerformed

    private void mitTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHOATActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitTHOATActionPerformed

    private void btnSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.setRole(role);
        frmS.setManv(manv);
        frmS.show();
        dispose();
    }//GEN-LAST:event_btnSACHActionPerformed

    private void btnPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.setRole(role);
        frmPN.setManv(manv);
        frmPN.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUNHAPActionPerformed

    private void btnPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.setRole(role);
        frmPM.setManv(manv);
        frmPM.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONActionPerformed

    private void btnPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.setRole(role);
        frmPMCT.setManv(manv);
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONCTActionPerformed

    private void mitNHANVIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNHANVIENActionPerformed
        frmNNHANVIEN frmNV = new frmNNHANVIEN();
        frmNV.setRole(role);
        frmNV.setManv(manv);
        frmNV.show();
        dispose();
    }//GEN-LAST:event_mitNHANVIENActionPerformed

    private void mitDOCGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOCGIAActionPerformed
        frmDOCGIA frmDG = new frmDOCGIA();
        frmDG.setRole(role);
        frmDG.setManv(manv);
        frmDG.show();
        dispose();
    }//GEN-LAST:event_mitDOCGIAActionPerformed

    private void mitSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.setRole(role);
        frmS.setManv(manv);
        frmS.show();
        dispose();
    }//GEN-LAST:event_mitSACHActionPerformed

    private void mitTACGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTACGIAActionPerformed
        frmTACGIA frmTG = new frmTACGIA();
        frmTG.setRole(role);
        frmTG.setManv(manv);
        frmTG.show();
        dispose();
    }//GEN-LAST:event_mitTACGIAActionPerformed

    private void mitNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNXBActionPerformed
        frmNXB frmN = new frmNXB();
        frmN.setRole(role);
        frmN.setManv(manv);
        frmN.show();
        dispose();
    }//GEN-LAST:event_mitNXBActionPerformed

    private void mitPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.setRole(role);
        frmPN.setManv(manv);
        frmPN.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUNHAPActionPerformed

    private void mitPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.setRole(role);
        frmPM.setManv(manv);
        frmPM.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONActionPerformed

    private void mitPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.setRole(role);
        frmPMCT.setManv(manv);
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONCTActionPerformed

    private void mitTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHONGKEActionPerformed
        frmTHONGKE frmTK = new frmTHONGKE();
        frmTK.setRole(role);
        frmTK.setManv(manv);
        frmTK.show();
        dispose();
    }//GEN-LAST:event_mitTHONGKEActionPerformed

    private void btnDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_btnDANGXUATActionPerformed

    private void mitDOIMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOIMKActionPerformed
        frmDOIMATKHAU frmDMK;
        try {
            frmDMK = new frmDOIMATKHAU();
            frmDMK.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitDOIMKActionPerformed

    private void btnDGXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGXOAActionPerformed
        xoaDocgia();
        laydulieuDocgia("");
    }//GEN-LAST:event_btnDGXOAActionPerformed

    private void btnDGCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGCAPNHATActionPerformed
        if(kiemloiDG() == false){
        return;
        }
        List<Docgia> listdg = new ArrayList<>();
        String sql1 = " WHERE sdt like '" + txtDGSDT.getText() + "' and madg != '" + txtMADG.getText() + "'";
        try {
            listdg = DocgiaDao.laydulieuDocgia(sql1);
        } catch (SQLException ex) {
            Logger.getLogger(frmNNHANVIEN.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!listdg.isEmpty()) {
            JOptionPane.showMessageDialog(this, "SĐT bị trùng lặp");
            listdg.clear();
            return;
        }
        capnhatDocgia();
        laydulieuDocgia("");
    }//GEN-LAST:event_btnDGCAPNHATActionPerformed

    private void btnDGTHEMMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGTHEMMOIActionPerformed
        if (kiemloiDG() == false) {
            return;
        }
        for (Docgia dg : list) {
            if (dg.getSdt().equals(txtDGSDT.getText())) {
                JOptionPane.showMessageDialog(this, "SĐT bị trùng lặp");
                return;
            }
        }
        themDocgia();
        laydulieuDocgia("");
    }//GEN-LAST:event_btnDGTHEMMOIActionPerformed

    private void btnDGSEACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGSEACHActionPerformed
        timkiemDocgia();
    }//GEN-LAST:event_btnDGSEACHActionPerformed

    private void tblDOCGIAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDOCGIAMouseClicked
        Docgia dg = list.get(tblDOCGIA.getSelectedRow());
        txtMADG.setText(dg.getMadg());
        txtTENDG.setText(dg.getTendg());
        txtDGSDT.setText(dg.getSdt());
        txtDGDIACHI.setText(dg.getDiachi());
        txtDGMATKHAU.setText(dg.getMk());
        btnDGHINH.setIcon(new ImageIcon(getClass().getResource("/IMGDG/" + dg.getHinhanh())));
    }//GEN-LAST:event_tblDOCGIAMouseClicked

    private void btnDGHINHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGHINHActionPerformed
        JFileChooser fch = new JFileChooser();
        int result = fch.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                //Lấy tên hình ảnh
                btnDGHINH.setIcon(new ImageIcon(fch.getSelectedFile().getPath()));
                this.hinhanh = fch.getSelectedFile().getName();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi chọn hình");
            }
        }
    }//GEN-LAST:event_btnDGHINHActionPerformed

    private void btnDGNHAPMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDGNHAPMOIActionPerformed
        txtMADG.setText("");
        txtTENDG.setText("");
        txtDGSDT.setText("");
        txtDGDIACHI.setText("");
        txtDGMATKHAU.setText("");
        btnDGHINH.setIcon(new ImageIcon(getClass().getResource("")));
        this.hinhanh = "";
    }//GEN-LAST:event_btnDGNHAPMOIActionPerformed

    private void mitPHIEUPHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUPHATActionPerformed
        frmPHIEUPHAT frmPP;
        frmPP = new frmPHIEUPHAT();
        frmPP.setRole(role);
        frmPP.setManv(manv);
        frmPP.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUPHATActionPerformed

    private void mitHDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHDSDActionPerformed
        JOptionPane.showMessageDialog(this, "Vào hệ thống để thực hiện 'Đăng nhập','Đăng xuất','Đổi mật khẩu'\r\n"
                + "Vào Quản lý để truy cập thông tin khách hàng , nhân viên , sản phẩm , nhập hàng \r\n"
                + "Vào thống kê để xem hóa đơn , hóa đơn chi tiết , bảng giá , doanh thu \r\n"
                + "Vào trợ giúp để xem thong tin phiên bản và hướng dẫn sử dụng \r\n"
                + "Sử dụng thanh Tool Bar để truy cập nhanh vào các mục tương ứng");
    }//GEN-LAST:event_mitHDSDActionPerformed

    private void mitTTPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTTPBActionPerformed
        JOptionPane.showMessageDialog(this, "Phần mềm quản lý thư viện \r\n" + "Phiên bản :  1.1.0.0 \r\n" + "Cập nhật ngày : 15/3/2019");
    }//GEN-LAST:event_mitTTPBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDOCGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDOCGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDOCGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDOCGIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDOCGIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DOCGIA;
    private javax.swing.JButton btnDANGXUAT;
    private javax.swing.JButton btnDGCAPNHAT;
    private javax.swing.JButton btnDGHINH;
    private javax.swing.JButton btnDGNHAPMOI;
    private javax.swing.JButton btnDGSEACH;
    private javax.swing.JButton btnDGTHEMMOI;
    private javax.swing.JButton btnDGXOA;
    private javax.swing.JButton btnPHIEUMUON;
    private javax.swing.JButton btnPHIEUMUONCT;
    private javax.swing.JButton btnPHIEUNHAP;
    private javax.swing.JButton btnSACH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBR;
    private javax.swing.JMenuItem mitDANGXUAT;
    private javax.swing.JMenuItem mitDOCGIA;
    private javax.swing.JMenuItem mitDOIMK;
    private javax.swing.JMenuItem mitHDSD;
    private javax.swing.JMenuItem mitNHANVIEN;
    private javax.swing.JMenuItem mitNXB;
    private javax.swing.JMenuItem mitPHIEUMUON;
    private javax.swing.JMenuItem mitPHIEUMUONCT;
    private javax.swing.JMenuItem mitPHIEUNHAP;
    private javax.swing.JMenuItem mitPHIEUPHAT;
    private javax.swing.JMenuItem mitSACH;
    private javax.swing.JMenuItem mitTACGIA;
    private javax.swing.JMenuItem mitTHOAT;
    private javax.swing.JMenuItem mitTHONGKE;
    private javax.swing.JMenuItem mitTTPB;
    private javax.swing.JRadioButton rdbMDG;
    private javax.swing.JRadioButton rdbSDT;
    private javax.swing.JRadioButton rdbTENDG;
    private javax.swing.JTable tblDOCGIA;
    private javax.swing.JTextArea txtDGDIACHI;
    private javax.swing.JTextField txtDGMATKHAU;
    private javax.swing.JTextField txtDGSDT;
    private javax.swing.JTextField txtMADG;
    private javax.swing.JTextField txtSEACH;
    private javax.swing.JTextField txtTENDG;
    // End of variables declaration//GEN-END:variables

    private void xoaDocgia() {
        String madg = txtMADG.getText();
        DocgiaDao.xoaDocgia(madg);
        JOptionPane.showMessageDialog(this, "Xóa độc giả thành công");
    }

    private void themDocgia() {
        String madg = null;
        int a;
        AD:
        for (int i = 1; i < 1000; i++) {
            a = i;
            String b = Integer.toString(a);
            if (b.length() == 1) {
                madg = "DG00" + a;
            } else if (b.length() == 2) {
                madg = "DG0" + a;
            } else if (b.length() > 2) {
                madg = "DG" + a;
            } else {
            }
            boolean khIsExixst = false;
            for (Docgia dg : list) {
                if (dg.getMadg().equals(madg)) {
                    khIsExixst = true;
                    break;
                }
            }
            if (!khIsExixst) {
                break;
            }
        }
        String ten = txtTENDG.getText();
        String sdt = txtDGSDT.getText();
        String diachi = txtDGDIACHI.getText();
        String matkhau = txtDGMATKHAU.getText();
        String hinh = this.hinhanh;

        Docgia dg = new Docgia(madg, ten, diachi, sdt, matkhau, hinh);
        DocgiaDao.themDocgia(dg);
        JOptionPane.showMessageDialog(this, "Thêm độc giả thành công");

    }

    private void timkiemDocgia() {
        String sql = "";
        if (rdbMDG.isSelected()) {
            sql = " WHERE madg like '%" + txtSEACH.getText() + "%'";
        } else if (rdbSDT.isSelected()) {
            sql = " WHERE sdt like '%" + txtSEACH.getText() + "%'";
        } else if (rdbTENDG.isSelected()) {
            sql = " WHERE tendg like N'%" + txtSEACH.getText() + "%'";
        } else {
        }
        laydulieuDocgia(sql);
    }

    private void capnhatDocgia() {
        String madg = txtMADG.getText();
        String ten = txtTENDG.getText();
        String sdt = txtDGSDT.getText();
        String diachi = txtDGDIACHI.getText();
        String matkhau = txtDGMATKHAU.getText();
        String hinh = this.hinhanh;

        Docgia dg = new Docgia(madg, ten, diachi, sdt, matkhau, hinh);
        DocgiaDao.capnhatDocgia(dg);
        JOptionPane.showMessageDialog(this, "Cập nhật độc giả thành công");
    }

    private boolean kiemloiDG() {
        if (txtTENDG.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên độc giả");
            return false;
        } else if (txtDGSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập SĐT độc giả");
            return false;
        } else if (txtDGDIACHI.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ độc giả");
            return false;
        } else if (txtDGMATKHAU.getText().trim().length() < 8 || txtDGMATKHAU.getText().trim().length() > 16) {
            JOptionPane.showMessageDialog(this, "Mật khẩu có độ dài từ 8 dến 16 kí tự");
            return false;
        } else if (hinhanh.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hình");
            return false;
        } else {
            try {
                int sdt = Integer.parseInt(txtDGSDT.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập SĐT bằng số");
                return false;
            }
        }
        return true;
    }

}
