/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmQLTV;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import model.Nhanvien;
import model.NhanvienDao;

/**
 *
 * @author My PC
 */
public class frmNNHANVIEN extends javax.swing.JFrame {

    /**
     * Creates new form frmMENU
     */
    List<Nhanvien> list = new ArrayList<>();
    private int currentindex;
    private String hinhanh = "";
    private int role;
    private String manv;

    public frmNNHANVIEN() {
        initComponents();
        this.setSize(990, 550);
        rdbQL.setSelected(true);
        rdbMANV.setSelected(true);
        lblBR.setIcon(new ImageIcon(getClass().getResource("/BR/brnv-2.jpg")));
        setLocationRelativeTo(null);
        laydulieuNhanvien("");

    }

    // set vai trò quản lý
    public void setRole(int role) {
        this.role = role;
        checkRole(role);
    }
// set mã nhân vên

    public void setManv(String manv) {
        this.manv = manv;
    }
// kiểm tra vai trò : 1 - Quản lý , 2 - Nhân viên

    public void checkRole(int role) {
        if (role == 1) {
            mitNHANVIEN.hide();
            mitTHONGKE.hide();
        }
    }

    private void laydulieuNhanvien(String sql) {
        try {
            list.clear();
            tblNHANVIEN.removeAll();
            list = NhanvienDao.laydulieuNhanvien(sql);
            fillToTableNhanvien();
            laydulieuNV();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }

    private void laydulieuNV() {
        try {
            this.currentindex = 0;
            if (list.size() == 1) {
                this.currentindex = 0;
            }
            Nhanvien nv = list.get(currentindex);
            txtMANV.setText(nv.getManv());
            txtTENNV.setText(nv.getTennv());
            txtNVDIACHI.setText(nv.getDiachi());
            txtNVEMAIL.setText(nv.getEmail());
            txtNVMATKHAU.setText(nv.getMk());
            txtNVNGAYSINH.setText(nv.getNgaysinh());
            txtNVSDT.setText(nv.getSdt());
            if (nv.getVaitro().equals("0")) {
                rdbQL.setSelected(true);
            } else {
                rdbNV.setSelected(true);
            }
            btnNVHINH.setIcon(new ImageIcon(getClass().getResource("/IMGNV/" + nv.getHinhanh())));
            this.hinhanh = nv.getHinhanh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDANGXUAT = new javax.swing.JButton();
        btnSACH = new javax.swing.JButton();
        btnPHIEUNHAP = new javax.swing.JButton();
        btnPHIEUMUON = new javax.swing.JButton();
        btnPHIEUMUONCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        NHANVIEN = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNHANVIEN = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnNVHINH = new javax.swing.JButton();
        txtMANV = new javax.swing.JTextField();
        txtTENNV = new javax.swing.JTextField();
        txtNVNGAYSINH = new javax.swing.JTextField();
        txtNVSDT = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtNVEMAIL = new javax.swing.JTextField();
        txtNVDIACHI = new javax.swing.JTextField();
        btnNVNHAPMOI = new javax.swing.JButton();
        btnNVTHEMMOI = new javax.swing.JButton();
        btnNVCAPNHAT = new javax.swing.JButton();
        btnNVXOA = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnNVSEACH = new javax.swing.JButton();
        rdbMANV = new javax.swing.JRadioButton();
        rdbTENNV = new javax.swing.JRadioButton();
        rdbEMAIL = new javax.swing.JRadioButton();
        rdbSDT = new javax.swing.JRadioButton();
        txtSEACH = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtNVMATKHAU = new javax.swing.JTextField();
        rdbQL = new javax.swing.JRadioButton();
        rdbNV = new javax.swing.JRadioButton();
        lblBR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDANGXUAT = new javax.swing.JMenuItem();
        mitDOIMK = new javax.swing.JMenuItem();
        mitTHOAT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitNHANVIEN = new javax.swing.JMenuItem();
        mitDOCGIA = new javax.swing.JMenuItem();
        mitSACH = new javax.swing.JMenuItem();
        mitTACGIA = new javax.swing.JMenuItem();
        mitNXB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitPHIEUNHAP = new javax.swing.JMenuItem();
        mitPHIEUMUON = new javax.swing.JMenuItem();
        mitPHIEUMUONCT = new javax.swing.JMenuItem();
        mitPHIEUPHAT = new javax.swing.JMenuItem();
        mitTHONGKE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHDSD = new javax.swing.JMenuItem();
        mitTTPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        btnDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        btnDANGXUAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        btnDANGXUAT.setText("Đăng xuất");
        btnDANGXUAT.setFocusable(false);
        btnDANGXUAT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDANGXUAT.setMaximumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setMinimumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setPreferredSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGXUATActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDANGXUAT);

        btnSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        btnSACH.setText("Sách");
        btnSACH.setFocusable(false);
        btnSACH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSACH.setMaximumSize(new java.awt.Dimension(91, 51));
        btnSACH.setMinimumSize(new java.awt.Dimension(91, 51));
        btnSACH.setPreferredSize(new java.awt.Dimension(91, 51));
        btnSACH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSACHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSACH);

        btnPHIEUNHAP.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        btnPHIEUNHAP.setText("Phiếu nhập");
        btnPHIEUNHAP.setFocusable(false);
        btnPHIEUNHAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUNHAP.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUNHAPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUNHAP);

        btnPHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        btnPHIEUMUON.setText("Phiếu mượn");
        btnPHIEUMUON.setFocusable(false);
        btnPHIEUMUON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUON.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUON);

        btnPHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUONCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        btnPHIEUMUONCT.setText("Phiếu mượn CT");
        btnPHIEUMUONCT.setFocusable(false);
        btnPHIEUMUONCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUONCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUONCT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        NHANVIEN.setBackground(new java.awt.Color(255, 255, 255));
        NHANVIEN.setOpaque(false);

        tblNHANVIEN.setBackground(new java.awt.Color(204, 255, 255));
        tblNHANVIEN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Số điện thoại", "Email", "Địa chỉ", "Vai trò", "Mật khẩu", "Hình ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNHANVIEN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNHANVIENMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNHANVIEN);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("Mã nhân viên");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("Tên nhân viên");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("Ngày sinh");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("Số điện thoại");

        btnNVHINH.setBackground(new java.awt.Color(255, 255, 255));
        btnNVHINH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVHINHActionPerformed(evt);
            }
        });

        txtMANV.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("Email");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 255));
        jLabel20.setText("Địa chỉ");

        btnNVNHAPMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNVNHAPMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnNVNHAPMOI.setText("Nhập mới");
        btnNVNHAPMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVNHAPMOIActionPerformed(evt);
            }
        });

        btnNVTHEMMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNVTHEMMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnNVTHEMMOI.setText("Thêm mới");
        btnNVTHEMMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVTHEMMOIActionPerformed(evt);
            }
        });

        btnNVCAPNHAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNVCAPNHAT.setForeground(new java.awt.Color(51, 51, 51));
        btnNVCAPNHAT.setText("Cập nhật");
        btnNVCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVCAPNHATActionPerformed(evt);
            }
        });

        btnNVXOA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNVXOA.setForeground(new java.awt.Color(51, 51, 51));
        btnNVXOA.setText("Xóa");
        btnNVXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVXOAActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel5.setOpaque(false);

        btnNVSEACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNVSEACH.setForeground(new java.awt.Color(51, 51, 51));
        btnNVSEACH.setText("SEACH");
        btnNVSEACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNVSEACHActionPerformed(evt);
            }
        });

        buttonGroup10.add(rdbMANV);
        rdbMANV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMANV.setForeground(new java.awt.Color(0, 0, 255));
        rdbMANV.setText("Mã nhân viên");

        buttonGroup10.add(rdbTENNV);
        rdbTENNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbTENNV.setForeground(new java.awt.Color(0, 0, 255));
        rdbTENNV.setText("Tên nhân viên");

        buttonGroup10.add(rdbEMAIL);
        rdbEMAIL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbEMAIL.setForeground(new java.awt.Color(0, 0, 255));
        rdbEMAIL.setText("Email");

        buttonGroup10.add(rdbSDT);
        rdbSDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbSDT.setForeground(new java.awt.Color(0, 0, 255));
        rdbSDT.setText("SĐT");

        txtSEACH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNVSEACH)
                .addGap(37, 37, 37))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rdbTENNV)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdbSDT)
                            .addComponent(rdbMANV)
                            .addComponent(rdbEMAIL))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(txtSEACH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(txtSEACH, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbMANV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbTENNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbEMAIL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbSDT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNVSEACH))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Vai trò");

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 0, 255));
        jLabel48.setText("Mật khẩu");

        buttonGroup1.add(rdbQL);
        rdbQL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbQL.setForeground(new java.awt.Color(255, 0, 0));
        rdbQL.setText("Quản lý");

        buttonGroup1.add(rdbNV);
        rdbNV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbNV.setForeground(new java.awt.Color(255, 0, 0));
        rdbNV.setText("Nhân viên");

        javax.swing.GroupLayout NHANVIENLayout = new javax.swing.GroupLayout(NHANVIEN);
        NHANVIEN.setLayout(NHANVIENLayout);
        NHANVIENLayout.setHorizontalGroup(
            NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NHANVIENLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(NHANVIENLayout.createSequentialGroup()
                        .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NHANVIENLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnNVNHAPMOI))
                            .addGroup(NHANVIENLayout.createSequentialGroup()
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTENNV)
                                    .addComponent(txtNVNGAYSINH)
                                    .addGroup(NHANVIENLayout.createSequentialGroup()
                                        .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(NHANVIENLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addComponent(rdbQL)
                                                .addGap(18, 18, 18)
                                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(rdbNV)
                                                    .addComponent(btnNVTHEMMOI))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)))))
                        .addGap(12, 12, 12)
                        .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NHANVIENLayout.createSequentialGroup()
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel48))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNVSDT)
                                    .addComponent(txtNVMATKHAU)))
                            .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(NHANVIENLayout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(btnNVCAPNHAT)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNVXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(23, 23, 23))
                                .addGroup(NHANVIENLayout.createSequentialGroup()
                                    .addComponent(jLabel19)
                                    .addGap(58, 58, 58)
                                    .addComponent(txtNVEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(NHANVIENLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtNVDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addComponent(btnNVHINH, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        NHANVIENLayout.setVerticalGroup(
            NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NHANVIENLayout.createSequentialGroup()
                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NHANVIENLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(NHANVIENLayout.createSequentialGroup()
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(txtMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(txtNVEMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(txtTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtNVDIACHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtNVNGAYSINH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtNVSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel48)
                                    .addComponent(txtNVMATKHAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rdbQL)
                                    .addComponent(rdbNV))
                                .addGap(14, 14, 14)
                                .addGroup(NHANVIENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnNVNHAPMOI)
                                    .addComponent(btnNVTHEMMOI)
                                    .addComponent(btnNVCAPNHAT)
                                    .addComponent(btnNVXOA)))
                            .addComponent(btnNVHINH, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NHANVIENLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        lblBR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBR.setName(""); // NOI18N
        lblBR.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(NHANVIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lblBR)
                    .addGap(0, 1005, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(NHANVIEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(lblBR)
                    .addGap(0, 392, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2494, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Hệ thống");

        mitDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        mitDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        mitDANGXUAT.setText("Đăng xuất");
        mitDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDANGXUATActionPerformed(evt);
            }
        });
        jMenu1.add(mitDANGXUAT);

        mitDOIMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondmk.jpg"))); // NOI18N
        mitDOIMK.setText("Đổi mật khẩu");
        mitDOIMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOIMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDOIMK);

        mitTHOAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconexit1.jpg"))); // NOI18N
        mitTHOAT.setText("Thoát");
        mitTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHOATActionPerformed(evt);
            }
        });
        jMenu1.add(mitTHOAT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mitNHANVIEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnv1.jpg"))); // NOI18N
        mitNHANVIEN.setText("Nhân viên");
        mitNHANVIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNHANVIENActionPerformed(evt);
            }
        });
        jMenu2.add(mitNHANVIEN);

        mitDOCGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondocgia1.jpg"))); // NOI18N
        mitDOCGIA.setText("Độc giả");
        mitDOCGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOCGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitDOCGIA);

        mitSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        mitSACH.setText("Sách");
        mitSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSACHActionPerformed(evt);
            }
        });
        jMenu2.add(mitSACH);

        mitTACGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icontacgia1.jpg"))); // NOI18N
        mitTACGIA.setText("Tác giả");
        mitTACGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTACGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitTACGIA);

        mitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnxb1.jpg"))); // NOI18N
        mitNXB.setText("Nhà xuất bản");
        mitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNXBActionPerformed(evt);
            }
        });
        jMenu2.add(mitNXB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mitPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        mitPHIEUNHAP.setText("Phiếu nhập sách");
        mitPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUNHAPActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUNHAP);

        mitPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        mitPHIEUMUON.setText("Phiếu mượn sách");
        mitPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUON);

        mitPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        mitPHIEUMUONCT.setText("Phiếu mượn sách chi tiết");
        mitPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONCTActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUONCT);

        mitPHIEUPHAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconpp.png"))); // NOI18N
        mitPHIEUPHAT.setText("Phiếu phạt");
        mitPHIEUPHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUPHATActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUPHAT);

        mitTHONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbdtk.jpg"))); // NOI18N
        mitTHONGKE.setText("Thống kê số liệu");
        mitTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHONGKEActionPerformed(evt);
            }
        });
        jMenu3.add(mitTHONGKE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mitHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconhdsd1.jpg"))); // NOI18N
        mitHDSD.setText("Hướng dẫn sử dụng");
        mitHDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHDSDActionPerformed(evt);
            }
        });
        jMenu4.add(mitHDSD);

        mitTTPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/gt_1.png"))); // NOI18N
        mitTTPB.setText("Thông tin phiên bản");
        mitTTPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTTPBActionPerformed(evt);
            }
        });
        jMenu4.add(mitTTPB);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 987, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void mitDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {                                            
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }                                           

    private void mitTHOATActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.exit(0);
    }                                        

    private void btnSACHActionPerformed(java.awt.event.ActionEvent evt) {                                        
        frmSACH frmS = new frmSACH();
        frmS.setRole(role);
        frmS.setManv(manv);
        frmS.show();
        dispose();
    }                                       

    private void btnPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {                                             
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.setRole(role);
        frmPN.setManv(manv);
        frmPN.show();
        dispose();
    }                                            

    private void btnPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {                                             
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.setRole(role);
        frmPM.setManv(manv);
        frmPM.show();
        dispose();
    }                                            

    private void btnPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {                                               
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.setRole(role);
        frmPMCT.setManv(manv);
        frmPMCT.show();
        dispose();
    }                                              

    private void mitNHANVIENActionPerformed(java.awt.event.ActionEvent evt) {                                            
        frmNNHANVIEN frmNV = new frmNNHANVIEN();
        frmNV.setRole(role);
        frmNV.setManv(manv);
        frmNV.show();
        dispose();
    }                                           

    private void mitDOCGIAActionPerformed(java.awt.event.ActionEvent evt) {                                          
        frmDOCGIA frmDG = new frmDOCGIA();
        frmDG.setRole(role);
        frmDG.setManv(manv);
        frmDG.show();
        dispose();
    }                                         

    private void mitSACHActionPerformed(java.awt.event.ActionEvent evt) {                                        
        frmSACH frmS = new frmSACH();
        frmS.setRole(role);
        frmS.setManv(manv);
        frmS.show();
        dispose();
    }                                       

    private void mitTACGIAActionPerformed(java.awt.event.ActionEvent evt) {                                          
        frmTACGIA frmTG = new frmTACGIA();
        frmTG.setRole(role);
        frmTG.setManv(manv);
        frmTG.show();
        dispose();
    }                                         

    private void mitNXBActionPerformed(java.awt.event.ActionEvent evt) {                                       
        frmNXB frmN = new frmNXB();
        frmN.setRole(role);
        frmN.setManv(manv);
        frmN.show();
        dispose();
    }                                      

    private void mitPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {                                             
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.setRole(role);
        frmPN.setManv(manv);
        frmPN.show();
        dispose();
    }                                            

    private void mitPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {                                             
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.setRole(role);
        frmPM.setManv(manv);
        frmPM.show();
        dispose();
    }                                            

    private void mitPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {                                               
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.setRole(role);
        frmPMCT.setManv(manv);
        frmPMCT.show();
        dispose();
    }                                              

    private void mitTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {                                           
        frmTHONGKE frmTK = new frmTHONGKE();
        frmTK.setRole(role);
        frmTK.setManv(manv);
        frmTK.show();
        dispose();
    }                                          

    private void btnDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {                                            
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }                                           

    private void mitDOIMKActionPerformed(java.awt.event.ActionEvent evt) {                                         
        frmDOIMATKHAU frmDMK;
        try {
            frmDMK = new frmDOIMATKHAU();
            frmDMK.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                        

    private void btnNVTHEMMOIActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if (kiemloiNV() == false) {
            return;
        }
        themNhanvien();
        laydulieuNhanvien("");
    }                                            

    private void btnNVCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {                                             
        if(kiemloiNV() == false){
        return;
        }
        List<Nhanvien> listnv = new ArrayList<>();
        String sql = " WHERE email like '" + txtNVEMAIL.getText() + "' and manv != '" + txtMANV.getText() + "'";
        try {
            listnv = NhanvienDao.laydulieuNhanvien(sql);
        } catch (SQLException ex) {
            Logger.getLogger(frmNNHANVIEN.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!listnv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email bị trùng lặp");
            listnv.clear();
            return;
        }
        String sql1 = " WHERE sdt like '" + txtNVSDT.getText() + "' and manv != '" + txtMANV.getText() + "'";
        try {
            listnv = NhanvienDao.laydulieuNhanvien(sql1);
        } catch (SQLException ex) {
            Logger.getLogger(frmNNHANVIEN.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (!listnv.isEmpty()) {
            JOptionPane.showMessageDialog(this, "SĐT bị trùng lặp");
            listnv.clear();
            return;
        }
        capnhatNhanvien();
        laydulieuNhanvien("");
    }                                            

    private void btnNVXOAActionPerformed(java.awt.event.ActionEvent evt) {                                         
        xoaNhanvien();
        currentindex = 0;
        laydulieuNhanvien("");
    }                                        

    private void btnNVSEACHActionPerformed(java.awt.event.ActionEvent evt) {                                           
        timkiemNhanvien();
    }                                          

    private void btnNVHINHActionPerformed(java.awt.event.ActionEvent evt) {                                          
        JFileChooser fch = new JFileChooser();
        int result = fch.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                //Lấy tên hình ảnh
                btnNVHINH.setIcon(new ImageIcon(fch.getSelectedFile().getPath()));
                this.hinhanh = fch.getSelectedFile().getName();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi chọn hình");
            }
        }
    }                                         

    private void tblNHANVIENMouseClicked(java.awt.event.MouseEvent evt) {                                         
        try {
            Nhanvien nv = list.get(tblNHANVIEN.getSelectedRow());
            txtMANV.setText(nv.getManv());
            txtTENNV.setText(nv.getTennv());
            txtNVDIACHI.setText(nv.getDiachi());
            txtNVEMAIL.setText(nv.getEmail());
            txtNVMATKHAU.setText(nv.getMk());
            txtNVNGAYSINH.setText(nv.getNgaysinh());
            txtNVSDT.setText(nv.getSdt());
            if (nv.getVaitro().equals("0")) {
                rdbQL.setSelected(true);
            } else {
                rdbNV.setSelected(true);
            }
            btnNVHINH.setIcon(new ImageIcon(getClass().getResource("/IMGNV/" + nv.getHinhanh())));
            this.hinhanh = nv.getHinhanh();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }                                        

    private void btnNVNHAPMOIActionPerformed(java.awt.event.ActionEvent evt) {                                             
        txtMANV.setText("");
        txtTENNV.setText("");
        txtNVDIACHI.setText("");
        txtNVEMAIL.setText("");
        txtNVMATKHAU.setText("");
        txtNVNGAYSINH.setText("");
        txtNVSDT.setText("");
        btnNVHINH.setIcon(new ImageIcon(getClass().getResource("")));
        this.hinhanh = "";
    }                                            

    private void mitPHIEUPHATActionPerformed(java.awt.event.ActionEvent evt) {                                             
        frmPHIEUPHAT frmPP;
        frmPP = new frmPHIEUPHAT();
        frmPP.setRole(role);
        frmPP.setManv(manv);
        frmPP.show();
        dispose();
    }                                            

    private void mitHDSDActionPerformed(java.awt.event.ActionEvent evt) {                                        
        JOptionPane.showMessageDialog(this, "Vào hệ thống để thực hiện 'Đăng nhập','Đăng xuất','Đổi mật khẩu'\r\n"
                + "Vào Quản lý để truy cập thông tin khách hàng , nhân viên , sản phẩm , nhập hàng \r\n"
                + "Vào thống kê để xem hóa đơn , hóa đơn chi tiết , bảng giá , doanh thu \r\n"
                + "Vào trợ giúp để xem thong tin phiên bản và hướng dẫn sử dụng \r\n"
                + "Sử dụng thanh Tool Bar để truy cập nhanh vào các mục tương ứng");
    }                                       

    private void mitTTPBActionPerformed(java.awt.event.ActionEvent evt) {                                        
        JOptionPane.showMessageDialog(this, "Phần mềm quản lý thư viện \r\n" + "Phiên bản :  1.1.0.0 \r\n" + "Cập nhật ngày : 15/3/2019");
    }                                       

    private void fillToTableNhanvien() {
        DefaultTableModel model = (DefaultTableModel) tblNHANVIEN.getModel();
        model.setRowCount(0);
        for (Nhanvien nv : list) {
            String vt = "";
            if (nv.getVaitro().equals(0)) {
                vt = "Quản lý";
            } else {
                vt = "Nhân viên";
            }
            Object[] row = new Object[]{nv.getManv(), nv.getTennv(), nv.getNgaysinh(), nv.getSdt(), nv.getEmail(), nv.getDiachi(), vt, nv.getMk(), nv.getHinhanh()};
            model.addRow(row);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNNHANVIEN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNNHANVIEN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel NHANVIEN;
    private javax.swing.JButton btnDANGXUAT;
    private javax.swing.JButton btnNVCAPNHAT;
    private javax.swing.JButton btnNVHINH;
    private javax.swing.JButton btnNVNHAPMOI;
    private javax.swing.JButton btnNVSEACH;
    private javax.swing.JButton btnNVTHEMMOI;
    private javax.swing.JButton btnNVXOA;
    private javax.swing.JButton btnPHIEUMUON;
    private javax.swing.JButton btnPHIEUMUONCT;
    private javax.swing.JButton btnPHIEUNHAP;
    private javax.swing.JButton btnSACH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBR;
    private javax.swing.JMenuItem mitDANGXUAT;
    private javax.swing.JMenuItem mitDOCGIA;
    private javax.swing.JMenuItem mitDOIMK;
    private javax.swing.JMenuItem mitHDSD;
    private javax.swing.JMenuItem mitNHANVIEN;
    private javax.swing.JMenuItem mitNXB;
    private javax.swing.JMenuItem mitPHIEUMUON;
    private javax.swing.JMenuItem mitPHIEUMUONCT;
    private javax.swing.JMenuItem mitPHIEUNHAP;
    private javax.swing.JMenuItem mitPHIEUPHAT;
    private javax.swing.JMenuItem mitSACH;
    private javax.swing.JMenuItem mitTACGIA;
    private javax.swing.JMenuItem mitTHOAT;
    private javax.swing.JMenuItem mitTHONGKE;
    private javax.swing.JMenuItem mitTTPB;
    private javax.swing.JRadioButton rdbEMAIL;
    private javax.swing.JRadioButton rdbMANV;
    private javax.swing.JRadioButton rdbNV;
    private javax.swing.JRadioButton rdbQL;
    private javax.swing.JRadioButton rdbSDT;
    private javax.swing.JRadioButton rdbTENNV;
    private javax.swing.JTable tblNHANVIEN;
    private javax.swing.JTextField txtMANV;
    private javax.swing.JTextField txtNVDIACHI;
    private javax.swing.JTextField txtNVEMAIL;
    private javax.swing.JTextField txtNVMATKHAU;
    private javax.swing.JTextField txtNVNGAYSINH;
    private javax.swing.JTextField txtNVSDT;
    private javax.swing.JTextField txtSEACH;
    private javax.swing.JTextField txtTENNV;
    // End of variables declaration                   

    private void themNhanvien() {
        String manv = null;
        int a;
        AD:
        for (int i = 1; i < 1000; i++) {
            a = i;
            String b = Integer.toString(a);
            if (b.length() == 1) {
                manv = "NV00" + a;
            } else if (b.length() == 2) {
                manv = "NV0" + a;
            } else if (b.length() > 2) {
                manv = "NV" + a;
            } else {
            }
            boolean khIsExixst = false;
            for (Nhanvien nv : list) {
                if (nv.getManv().equals(manv)) {
                    khIsExixst = true;
                    break;
                }
            }
            if (!khIsExixst) {
                break;
            }
        }
        String tennv = txtTENNV.getText();
        String diachi = txtNVDIACHI.getText();
        String email = txtNVEMAIL.getText();
        String mk = txtNVMATKHAU.getText();
        String ngaysinh = txtNVNGAYSINH.getText();
        String sdt = txtNVSDT.getText();
        String vt = "";
        if (rdbQL.isSelected()) {
            vt = "0";
        } else {
            vt = "1";
        }
        String hinh = hinhanh;
        Nhanvien nv = new Nhanvien(manv, tennv, ngaysinh, sdt, email, diachi, vt, mk, hinh);
        NhanvienDao.themNhanvien(nv);
        JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công");
    }

    private void capnhatNhanvien() {
        String manv = txtMANV.getText();
        String tennv = txtTENNV.getText();
        String diachi = txtNVDIACHI.getText();
        String email = txtNVEMAIL.getText();
        String mk = txtNVMATKHAU.getText();
        String ngaysinh = txtNVNGAYSINH.getText();
        String sdt = txtNVSDT.getText();
        String vt = "";
        if (rdbQL.isSelected()) {
            vt = "0";
        } else {
            vt = "1";
        }
        String hinh = hinhanh;
        Nhanvien nv = new Nhanvien(manv, tennv, ngaysinh, sdt, email, diachi, vt, mk, hinh);
        NhanvienDao.capnhatNhanvien(nv);
        JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công");
    }

    private void xoaNhanvien() {
        if (txtMANV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã nhân viên");
            return;
        } else {
            boolean ckmals = false;
            for (Nhanvien nv : list) {
                if (nv.getManv().equals(txtMANV.getText())) {
                    ckmals = true;
                    break;
                }
            }
            if (!ckmals) {
                JOptionPane.showMessageDialog(this, "Mã nhân viên không tồn tại");
                return;
            }
        }
        String manv = txtMANV.getText();
        NhanvienDao.xoaNhanvien(manv);
        JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công");
    }

    private boolean kiemloiNV() {
        if (txtTENNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên nhân viên");
            return false;
        } else if (txtNVNGAYSINH.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh nhân viên");
            return false;
        } else if (txtNVEMAIL.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập email nhân viên");
            return false;
        } else if (txtNVDIACHI.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ nhân viên");
            return false;
        } else if (txtNVSDT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập sđt nhân viên");
            return false;
        } else if (txtNVMATKHAU.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu nhân viên");
            return false;
        } else if (this.hinhanh.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hình nhân viên");
            return false;
        } else {
            String ktemail = "^[\\w!#$%&’*+/=?`{|}~^-]+(?:\\.[\\w!#$%&’*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
            java.util.regex.Pattern p = java.util.regex.Pattern.compile(ktemail);
            java.util.regex.Matcher m = p.matcher(txtNVEMAIL.getText());
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng Email vui lòng nhập lại/Định dạng : chuỗi + @ + chuỗi+.+chuỗi/ VD:trantien123@gmail.com");
                return false;
            } else {

            }

            try {
                int sdt = Integer.parseInt(txtNVSDT.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập sđt bằng số");
                return false;
            }
            if (txtNVMATKHAU.getText().length() < 8 || txtNVMATKHAU.getText().length() > 16) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập mật khẩu nhân viên từ 8 đến 16 kí tự");
                return false;
            }
        }
        return true;
    }

    private void timkiemNhanvien() {
        String sql = "";
        if (rdbMANV.isSelected()) {
            sql = " WHERE manv like '%" + txtSEACH.getText() + "%'";
        } else if (rdbEMAIL.isSelected()) {
            sql = " WHERE email like '%" + txtSEACH.getText() + "%'";
        } else if (rdbSDT.isSelected()) {
            sql = " WHERE sdt like '%" + txtSEACH.getText() + "%'";
        } else if (rdbTENNV.isSelected()) {
            sql = " WHERE tennv like N'%" + txtSEACH.getText() + "%'";
        }
        laydulieuNhanvien(sql);
    }
}
