/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmQLTV;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Docgia;
import model.DocgiaDao;
import model.Nhanvien;
import model.NhanvienDao;
import model.Phieumuon;
import model.PhieumuonCT;
import model.PhieumuonCTDao;
import model.PhieumuonDao;
import model.Phieuphat;
import model.PhieuphatDao;
import model.Sach;
import model.SachDao;

/**
 *
 * @author My PC
 */
public class frmPHIEUMUON extends javax.swing.JFrame {

    /**
     * Creates new form frmMENU
     */
    List<Phieumuon> list = new ArrayList<>();
    private int currentindex;
    private int cktt1;
    private int cktt2;
    private int role;
    private String manv;

    public frmPHIEUMUON() {
        initComponents();
        rdbDT.setSelected(true);
        rdbMPM.setSelected(true);
        this.setSize(760, 580);
        lblBR.setIcon(new ImageIcon(getClass().getResource("/BR/brpm-1.jpg")));
        setLocationRelativeTo(null);
        laydulieuPhieumuon("");

    }

    // set vai trò quản lý
    public void setRole(int role) {
        this.role = role;
        checkRole(role);
    }
// set mã nhân vên

    public void setManv(String manv) {
        this.manv = manv;
    }
// kiểm tra vai trò : 1 - Quản lý , 2 - Nhân viên

    public void checkRole(int role) {
        if (role == 1) {
            mitNHANVIEN.hide();
            mitTHONGKE.hide();
        }
    }

    private void laydulieuPhieumuon(String sql) {
        try {
            list.clear();
            tblPHIEUMUON.removeAll();
            list = PhieumuonDao.laydulieuPhieumuon(sql);
            fillToTablePhieumuon();
            laydulieuPM();
        } catch (SQLException ex) {
            Logger.getLogger(frmPHIEUMUON.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void fillToTablePhieumuon() {
        DefaultTableModel model = (DefaultTableModel) tblPHIEUMUON.getModel();
        model.setRowCount(0);
        for (Phieumuon pm : list) {
            String tt;
            if (pm.getTrangthai() == 0) {
                tt = "Đã trả";
            } else {
                tt = "Chưa trả";
            }
            Object[] row = new Object[]{pm.getMaphieumuon(), pm.getMadg(), pm.getManv(), pm.getNgaymuon(), pm.getNgaytra(), tt};
            model.addRow(row);
        }
    }

    private void laydulieuPM() {
        try {
            this.currentindex = 0;
            if (list.size() == 1) {
                this.currentindex = 0;
            }
            Phieumuon pm = list.get(currentindex);
            txtMAPM.setText(pm.getMaphieumuon());
            txtPMMANV.setText(pm.getManv());
            txtPMMADOCGIA.setText(pm.getMadg());
            txtPMNGAYMUON.setText(pm.getNgaymuon());
            txtPMNGAYTRA.setText(pm.getNgaytra());
            if (pm.getTrangthai() == 0) {
                rdbDT.setSelected(true);
                cktt1 = 1;
            } else {
                rdbCT.setSelected(true);
                cktt1 = 2;
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy phiếu mượn");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDANGXUAT = new javax.swing.JButton();
        btnSACH = new javax.swing.JButton();
        btnPHIEUNHAP = new javax.swing.JButton();
        btnPHIEUMUON = new javax.swing.JButton();
        btnPHIEUMUONCT = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        PHIEUMUON = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txtMAPM = new javax.swing.JTextField();
        txtPMMADOCGIA = new javax.swing.JTextField();
        txtPMMANV = new javax.swing.JTextField();
        txtPMNGAYMUON = new javax.swing.JTextField();
        txtPMNGAYTRA = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblPHIEUMUON = new javax.swing.JTable();
        btnPMNHAPMOI = new javax.swing.JButton();
        btnPMTHEMMOI = new javax.swing.JButton();
        btnPMCAPNHAT = new javax.swing.JButton();
        btnPMXOA = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btnPMSEACH = new javax.swing.JButton();
        rdbMPM = new javax.swing.JRadioButton();
        rdbMDG = new javax.swing.JRadioButton();
        rdbTT = new javax.swing.JRadioButton();
        txtSEACH = new javax.swing.JTextField();
        rdbDT = new javax.swing.JRadioButton();
        rdbCT = new javax.swing.JRadioButton();
        lblBR = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitDANGXUAT = new javax.swing.JMenuItem();
        mitDOIMK = new javax.swing.JMenuItem();
        mitTHOAT = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mitNHANVIEN = new javax.swing.JMenuItem();
        mitDOCGIA = new javax.swing.JMenuItem();
        mitSACH = new javax.swing.JMenuItem();
        mitTACGIA = new javax.swing.JMenuItem();
        mitNXB = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mitPHIEUNHAP = new javax.swing.JMenuItem();
        mitPHIEUMUON = new javax.swing.JMenuItem();
        mitPHIEUMUONCT = new javax.swing.JMenuItem();
        mitPHIEUPHAT = new javax.swing.JMenuItem();
        mitTHONGKE = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mitHDSD = new javax.swing.JMenuItem();
        mitTTPB = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ THƯ VIỆN");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setToolTipText("");

        btnDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        btnDANGXUAT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        btnDANGXUAT.setText("Đăng xuất");
        btnDANGXUAT.setFocusable(false);
        btnDANGXUAT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDANGXUAT.setMaximumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setMinimumSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setPreferredSize(new java.awt.Dimension(91, 51));
        btnDANGXUAT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDANGXUATActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDANGXUAT);

        btnSACH.setBackground(new java.awt.Color(255, 255, 255));
        btnSACH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        btnSACH.setText("Sách");
        btnSACH.setFocusable(false);
        btnSACH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSACH.setMaximumSize(new java.awt.Dimension(91, 51));
        btnSACH.setMinimumSize(new java.awt.Dimension(91, 51));
        btnSACH.setPreferredSize(new java.awt.Dimension(91, 51));
        btnSACH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSACHActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSACH);

        btnPHIEUNHAP.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUNHAP.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        btnPHIEUNHAP.setText("Phiếu nhập");
        btnPHIEUNHAP.setFocusable(false);
        btnPHIEUNHAP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUNHAP.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUNHAP.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUNHAPActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUNHAP);

        btnPHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUON.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        btnPHIEUMUON.setText("Phiếu mượn");
        btnPHIEUMUON.setFocusable(false);
        btnPHIEUMUON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUON.setMaximumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setMinimumSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setPreferredSize(new java.awt.Dimension(91, 51));
        btnPHIEUMUON.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUON);

        btnPHIEUMUONCT.setBackground(new java.awt.Color(255, 255, 255));
        btnPHIEUMUONCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        btnPHIEUMUONCT.setText("Phiếu mượn CT");
        btnPHIEUMUONCT.setFocusable(false);
        btnPHIEUMUONCT.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPHIEUMUONCT.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPHIEUMUONCTActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPHIEUMUONCT);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        PHIEUMUON.setBackground(new java.awt.Color(255, 255, 255));
        PHIEUMUON.setOpaque(false);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 255));
        jLabel32.setText("Mã phiếu mượn");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 255));
        jLabel33.setText("Mã độc giả");

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 255));
        jLabel34.setText("Mã nhân viên");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 255));
        jLabel35.setText("Ngày mượn");

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 255));
        jLabel36.setText("Ngày hết hạn");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 255));
        jLabel37.setText("Trạng thái");

        txtMAPM.setBackground(new java.awt.Color(204, 255, 255));
        txtMAPM.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMAPM.setEnabled(false);

        tblPHIEUMUON.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã phiếu mượn", "Mã độc giả", "Mã nhân viên", "Ngày mượn", "Ngày hết hạn", "Trạng thái"
            }
        ));
        tblPHIEUMUON.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPHIEUMUONMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblPHIEUMUON);

        btnPMNHAPMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMNHAPMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnPMNHAPMOI.setText("Nhập mới");
        btnPMNHAPMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMNHAPMOIActionPerformed(evt);
            }
        });

        btnPMTHEMMOI.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMTHEMMOI.setForeground(new java.awt.Color(51, 51, 51));
        btnPMTHEMMOI.setText("Thêm mới");
        btnPMTHEMMOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMTHEMMOIActionPerformed(evt);
            }
        });

        btnPMCAPNHAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMCAPNHAT.setForeground(new java.awt.Color(51, 51, 51));
        btnPMCAPNHAT.setText("Cập nhật");
        btnPMCAPNHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMCAPNHATActionPerformed(evt);
            }
        });

        btnPMXOA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMXOA.setForeground(new java.awt.Color(51, 51, 51));
        btnPMXOA.setText("Xóa");
        btnPMXOA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMXOAActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel9.setOpaque(false);

        btnPMSEACH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPMSEACH.setForeground(new java.awt.Color(51, 51, 51));
        btnPMSEACH.setText("SEACH");
        btnPMSEACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPMSEACHActionPerformed(evt);
            }
        });

        buttonGroup10.add(rdbMPM);
        rdbMPM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMPM.setForeground(new java.awt.Color(0, 0, 255));
        rdbMPM.setText("Mã phiếu mượn");

        buttonGroup10.add(rdbMDG);
        rdbMDG.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbMDG.setForeground(new java.awt.Color(0, 0, 255));
        rdbMDG.setText("Mã độc giả");

        buttonGroup10.add(rdbTT);
        rdbTT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbTT.setForeground(new java.awt.Color(0, 0, 255));
        rdbTT.setText("Trạng thái");

        txtSEACH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPMSEACH)
                .addGap(38, 38, 38))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdbMPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdbMDG)
                    .addComponent(txtSEACH)
                    .addComponent(rdbTT))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSEACH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbMPM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbMDG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdbTT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPMSEACH))
        );

        buttonGroup1.add(rdbDT);
        rdbDT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbDT.setForeground(new java.awt.Color(255, 0, 0));
        rdbDT.setText("Đã trả");

        buttonGroup1.add(rdbCT);
        rdbCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rdbCT.setForeground(new java.awt.Color(255, 0, 0));
        rdbCT.setText("Chưa trả");

        javax.swing.GroupLayout PHIEUMUONLayout = new javax.swing.GroupLayout(PHIEUMUON);
        PHIEUMUON.setLayout(PHIEUMUONLayout);
        PHIEUMUONLayout.setHorizontalGroup(
            PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHIEUMUONLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane7)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PHIEUMUONLayout.createSequentialGroup()
                        .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PHIEUMUONLayout.createSequentialGroup()
                                .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel33)
                                    .addComponent(jLabel34))
                                .addGap(26, 26, 26)
                                .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMAPM)
                                    .addComponent(txtPMMADOCGIA)
                                    .addComponent(txtPMMANV, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE))
                                .addGap(34, 34, 34)
                                .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel36)
                                    .addComponent(jLabel37))
                                .addGap(30, 30, 30)
                                .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPMNGAYTRA)
                                    .addComponent(txtPMNGAYMUON)
                                    .addGroup(PHIEUMUONLayout.createSequentialGroup()
                                        .addComponent(rdbDT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                        .addComponent(rdbCT))))
                            .addGroup(PHIEUMUONLayout.createSequentialGroup()
                                .addComponent(btnPMNHAPMOI)
                                .addGap(27, 27, 27)
                                .addComponent(btnPMTHEMMOI)
                                .addGap(34, 34, 34)
                                .addComponent(btnPMCAPNHAT)
                                .addGap(27, 27, 27)
                                .addComponent(btnPMXOA, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        PHIEUMUONLayout.setVerticalGroup(
            PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHIEUMUONLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PHIEUMUONLayout.createSequentialGroup()
                        .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel35)
                            .addComponent(txtMAPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPMNGAYMUON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(jLabel36)
                            .addComponent(txtPMMADOCGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPMNGAYTRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jLabel37)
                            .addComponent(txtPMMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdbDT)
                            .addComponent(rdbCT))
                        .addGap(28, 28, 28)
                        .addGroup(PHIEUMUONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPMNHAPMOI)
                            .addComponent(btnPMTHEMMOI)
                            .addComponent(btnPMCAPNHAT)
                            .addComponent(btnPMXOA)))
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        lblBR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBR.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBR.setName(""); // NOI18N
        lblBR.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PHIEUMUON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblBR)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(PHIEUMUON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(lblBR)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 2496, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Hệ thống");

        mitDANGXUAT.setBackground(new java.awt.Color(255, 255, 255));
        mitDANGXUAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondx1.jpg"))); // NOI18N
        mitDANGXUAT.setText("Đăng xuất");
        mitDANGXUAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDANGXUATActionPerformed(evt);
            }
        });
        jMenu1.add(mitDANGXUAT);

        mitDOIMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondmk.jpg"))); // NOI18N
        mitDOIMK.setText("Đổi mật khẩu");
        mitDOIMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOIMKActionPerformed(evt);
            }
        });
        jMenu1.add(mitDOIMK);

        mitTHOAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconexit1.jpg"))); // NOI18N
        mitTHOAT.setText("Thoát");
        mitTHOAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHOATActionPerformed(evt);
            }
        });
        jMenu1.add(mitTHOAT);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản lý");

        mitNHANVIEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnv1.jpg"))); // NOI18N
        mitNHANVIEN.setText("Nhân viên");
        mitNHANVIEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNHANVIENActionPerformed(evt);
            }
        });
        jMenu2.add(mitNHANVIEN);

        mitDOCGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icondocgia1.jpg"))); // NOI18N
        mitDOCGIA.setText("Độc giả");
        mitDOCGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitDOCGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitDOCGIA);

        mitSACH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbook1.jpg"))); // NOI18N
        mitSACH.setText("Sách");
        mitSACH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSACHActionPerformed(evt);
            }
        });
        jMenu2.add(mitSACH);

        mitTACGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/icontacgia1.jpg"))); // NOI18N
        mitTACGIA.setText("Tác giả");
        mitTACGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTACGIAActionPerformed(evt);
            }
        });
        jMenu2.add(mitTACGIA);

        mitNXB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconnxb1.jpg"))); // NOI18N
        mitNXB.setText("Nhà xuất bản");
        mitNXB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitNXBActionPerformed(evt);
            }
        });
        jMenu2.add(mitNXB);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Thống kê");

        mitPHIEUNHAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieunhapsach1.jpg"))); // NOI18N
        mitPHIEUNHAP.setText("Phiếu nhập sách");
        mitPHIEUNHAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUNHAPActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUNHAP);

        mitPHIEUMUON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuon1.jpg"))); // NOI18N
        mitPHIEUMUON.setText("Phiếu mượn sách");
        mitPHIEUMUON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUON);

        mitPHIEUMUONCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconphieumuonct1.jpg"))); // NOI18N
        mitPHIEUMUONCT.setText("Phiếu mượn sách chi tiết");
        mitPHIEUMUONCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUMUONCTActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUMUONCT);

        mitPHIEUPHAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconpp.png"))); // NOI18N
        mitPHIEUPHAT.setText("Phiếu phạt");
        mitPHIEUPHAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitPHIEUPHATActionPerformed(evt);
            }
        });
        jMenu3.add(mitPHIEUPHAT);

        mitTHONGKE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconbdtk.jpg"))); // NOI18N
        mitTHONGKE.setText("Thống kê số liệu");
        mitTHONGKE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTHONGKEActionPerformed(evt);
            }
        });
        jMenu3.add(mitTHONGKE);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Trợ giúp");

        mitHDSD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/iconhdsd1.jpg"))); // NOI18N
        mitHDSD.setText("Hướng dẫn sử dụng");
        mitHDSD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitHDSDActionPerformed(evt);
            }
        });
        jMenu4.add(mitHDSD);

        mitTTPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/gt_1.png"))); // NOI18N
        mitTTPB.setText("Thông tin phiên bản");
        mitTTPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitTTPBActionPerformed(evt);
            }
        });
        jMenu4.add(mitTTPB);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("empty-statement")
    private void mitDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_mitDANGXUATActionPerformed

    private void mitTHOATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHOATActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mitTHOATActionPerformed

    private void btnSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.setRole(role);
        frmS.setManv(manv);
        frmS.show();
        dispose();
    }//GEN-LAST:event_btnSACHActionPerformed

    private void btnPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.setRole(role);
        frmPN.setManv(manv);
        frmPN.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUNHAPActionPerformed

    private void btnPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.setRole(role);
        frmPM.setManv(manv);
        frmPM.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONActionPerformed

    private void btnPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.setRole(role);
        frmPMCT.setManv(manv);
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_btnPHIEUMUONCTActionPerformed

    private void mitNHANVIENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNHANVIENActionPerformed
        frmNNHANVIEN frmNV = new frmNNHANVIEN();
        frmNV.setRole(role);
        frmNV.setManv(manv);
        frmNV.show();
        dispose();
    }//GEN-LAST:event_mitNHANVIENActionPerformed

    private void mitDOCGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOCGIAActionPerformed
        frmDOCGIA frmDG = new frmDOCGIA();
        frmDG.setRole(role);
        frmDG.setManv(manv);
        frmDG.show();
        dispose();
    }//GEN-LAST:event_mitDOCGIAActionPerformed

    private void mitSACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSACHActionPerformed
        frmSACH frmS = new frmSACH();
        frmS.setRole(role);
        frmS.setManv(manv);
        frmS.show();
        dispose();
    }//GEN-LAST:event_mitSACHActionPerformed

    private void mitTACGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTACGIAActionPerformed
        frmTACGIA frmTG = new frmTACGIA();
        frmTG.setRole(role);
        frmTG.setManv(manv);
        frmTG.show();
        dispose();
    }//GEN-LAST:event_mitTACGIAActionPerformed

    private void mitNXBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitNXBActionPerformed
        frmNXB frmN = new frmNXB();
        frmN.setRole(role);
        frmN.setManv(manv);
        frmN.show();
        dispose();
    }//GEN-LAST:event_mitNXBActionPerformed

    private void mitPHIEUNHAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUNHAPActionPerformed
        frmPHIEUNHAP frmPN;
        frmPN = new frmPHIEUNHAP();
        frmPN.setRole(role);
        frmPN.setManv(manv);
        frmPN.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUNHAPActionPerformed

    private void mitPHIEUMUONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONActionPerformed
        frmPHIEUMUON frmPM = new frmPHIEUMUON();
        frmPM.setRole(role);
        frmPM.setManv(manv);
        frmPM.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONActionPerformed

    private void mitPHIEUMUONCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUMUONCTActionPerformed
        frmPHIEUMUONCT frmPMCT = new frmPHIEUMUONCT();
        frmPMCT.setRole(role);
        frmPMCT.setManv(manv);
        frmPMCT.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUMUONCTActionPerformed

    private void mitTHONGKEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTHONGKEActionPerformed
        frmTHONGKE frmTK = new frmTHONGKE();
        frmTK.setRole(role);
        frmTK.setManv(manv);
        frmTK.show();
        dispose();
    }//GEN-LAST:event_mitTHONGKEActionPerformed

    private void btnPMTHEMMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMTHEMMOIActionPerformed
        if (kiemloiPM() == false) {
            return;
        }
        for (Phieumuon pm : list) {
            if (pm.getMadg().equals(txtPMMADOCGIA.getText()) && pm.getTrangthai() != 0) {
                List<Phieuphat> pp = new ArrayList<>();
                try {
                    pp = PhieuphatDao.layttPhieuphat(" Where mapm like '" + pm.getMaphieumuon() + "'");
                } catch (SQLException ex) {
                    Logger.getLogger(frmPHIEUMUON.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (!pp.isEmpty()) {
                    Phieuphat p = pp.get(0);
                    if (p.getTrangthai().equals("1")) {
                        JOptionPane.showMessageDialog(this, "Phiếu mượn trước độc giả chưa trả sách");
                        return;
                    } else {
                        break;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Phiếu mượn trước độc giả chưa trả sách");
                    return;
                }
            } else {
            }
        }

        themPM();
        laydulieuPhieumuon("");
        laydulieuPM();
    }//GEN-LAST:event_btnPMTHEMMOIActionPerformed

    private void btnPMCAPNHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMCAPNHATActionPerformed
        cktt2 = rdbDT.isSelected() ? 1 : 2;
        capnhatPhieumuon();
        if (cktt1 == 1 && cktt1 != cktt2) {
            try {
                PhieumuonDao.capnhatsoluongSachMuon(txtMAPM.getText());
            } catch (SQLException ex) {
                Logger.getLogger(frmPHIEUMUON.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (cktt1 == 2 && cktt1 != cktt2) {
            try {
                PhieumuonDao.capnhatsoluongSachTra(txtMAPM.getText());
            } catch (SQLException ex) {
                Logger.getLogger(frmPHIEUMUON.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        laydulieuPhieumuon("");
        laydulieuPM();
    }//GEN-LAST:event_btnPMCAPNHATActionPerformed

    private void btnPMXOAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMXOAActionPerformed
        String mapm = txtMAPM.getText();
        List<PhieumuonCT> pmct = new ArrayList<>();
        try {
            pmct = PhieumuonCTDao.laydulieuPhieumuonCT(" Where maphieumuon like '" + mapm + "'");
        } catch (SQLException ex) {
            Logger.getLogger(frmPHIEUMUON.class.getName()).log(Level.SEVERE, null, ex);
        }
        xoaPhieumuon();
        for (PhieumuonCT p : pmct) {
            String sql = " WHERE masach like '" + p.getMasach() + "'";
            List<Sach> sach = null;
            try {
                sach = SachDao.laydulieuSach(sql);
            } catch (SQLException ex) {
                Logger.getLogger(frmPHIEUMUONCT.class.getName()).log(Level.SEVERE, null, ex);
            }
            Sach s = sach.get(0);
            int sl = s.getSoluong() + 1;
            Sach sa = new Sach(s.getMasach(), s.getTensach(), s.getHinhanh(), s.getMatacgia(), s.getLoai(), sl, s.getManxb(), s.getNamxb(), s.getFiles());
            SachDao.capnhatSach(sa);
            PhieumuonCTDao.xoaPhieumuonCT(p.getMaphieumuonct());
        }
        currentindex = 0;
        laydulieuPhieumuon("");
    }//GEN-LAST:event_btnPMXOAActionPerformed

    private void btnPMSEACHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMSEACHActionPerformed
        timkiemPhieumuon();
    }//GEN-LAST:event_btnPMSEACHActionPerformed

    @SuppressWarnings("empty-statement")
    private void btnDANGXUATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDANGXUATActionPerformed
        frmDANGNHAP frmDN;
        try {
            frmDN = new frmDANGNHAP();;
            frmDN.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex1) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex1);
        }
    }//GEN-LAST:event_btnDANGXUATActionPerformed

    private void mitDOIMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitDOIMKActionPerformed
        frmDOIMATKHAU frmDMK;
        try {
            frmDMK = new frmDOIMATKHAU();
            frmDMK.show();
            dispose();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(frmDANGNHAP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mitDOIMKActionPerformed

    private void tblPHIEUMUONMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPHIEUMUONMouseClicked
        try {
            Phieumuon pm = list.get(tblPHIEUMUON.getSelectedRow());
            txtMAPM.setText(pm.getMaphieumuon());
            txtPMMANV.setText(pm.getManv());
            txtPMMADOCGIA.setText(pm.getMadg());
            txtPMNGAYMUON.setText(pm.getNgaymuon());
            txtPMNGAYTRA.setText(pm.getNgaytra());
            if (pm.getTrangthai() == 0) {
                rdbDT.setSelected(true);
                cktt1 = 1;
            } else {
                rdbCT.setSelected(true);
                cktt1 = 2;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dữ liệu trống");
        }
    }//GEN-LAST:event_tblPHIEUMUONMouseClicked

    private void btnPMNHAPMOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPMNHAPMOIActionPerformed
        txtMAPM.setText("");
        txtPMMANV.setText("");
        txtPMMADOCGIA.setText("");
        txtPMNGAYMUON.setText("");
        txtPMNGAYTRA.setText("");
        rdbDT.setSelected(false);
        rdbCT.setSelected(false);
    }//GEN-LAST:event_btnPMNHAPMOIActionPerformed

    private void mitPHIEUPHATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitPHIEUPHATActionPerformed
        frmPHIEUPHAT frmPP;
        frmPP = new frmPHIEUPHAT();
        frmPP.setRole(role);
        frmPP.setManv(manv);
        frmPP.show();
        dispose();
    }//GEN-LAST:event_mitPHIEUPHATActionPerformed

    private void mitHDSDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitHDSDActionPerformed
        JOptionPane.showMessageDialog(this, "Vào hệ thống để thực hiện 'Đăng nhập','Đăng xuất','Đổi mật khẩu'\r\n"
                + "Vào Quản lý để truy cập thông tin khách hàng , nhân viên , sản phẩm , nhập hàng \r\n"
                + "Vào thống kê để xem hóa đơn , hóa đơn chi tiết , bảng giá , doanh thu \r\n"
                + "Vào trợ giúp để xem thong tin phiên bản và hướng dẫn sử dụng \r\n"
                + "Sử dụng thanh Tool Bar để truy cập nhanh vào các mục tương ứng");
    }//GEN-LAST:event_mitHDSDActionPerformed

    private void mitTTPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitTTPBActionPerformed
        JOptionPane.showMessageDialog(this, "Phần mềm quản lý thư viện \r\n" + "Phiên bản :  1.1.0.0 \r\n" + "Cập nhật ngày : 15/3/2019");
    }//GEN-LAST:event_mitTTPBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPHIEUMUON.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmPHIEUMUON().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PHIEUMUON;
    private javax.swing.JButton btnDANGXUAT;
    private javax.swing.JButton btnPHIEUMUON;
    private javax.swing.JButton btnPHIEUMUONCT;
    private javax.swing.JButton btnPHIEUNHAP;
    private javax.swing.JButton btnPMCAPNHAT;
    private javax.swing.JButton btnPMNHAPMOI;
    private javax.swing.JButton btnPMSEACH;
    private javax.swing.JButton btnPMTHEMMOI;
    private javax.swing.JButton btnPMXOA;
    private javax.swing.JButton btnSACH;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblBR;
    private javax.swing.JMenuItem mitDANGXUAT;
    private javax.swing.JMenuItem mitDOCGIA;
    private javax.swing.JMenuItem mitDOIMK;
    private javax.swing.JMenuItem mitHDSD;
    private javax.swing.JMenuItem mitNHANVIEN;
    private javax.swing.JMenuItem mitNXB;
    private javax.swing.JMenuItem mitPHIEUMUON;
    private javax.swing.JMenuItem mitPHIEUMUONCT;
    private javax.swing.JMenuItem mitPHIEUNHAP;
    private javax.swing.JMenuItem mitPHIEUPHAT;
    private javax.swing.JMenuItem mitSACH;
    private javax.swing.JMenuItem mitTACGIA;
    private javax.swing.JMenuItem mitTHOAT;
    private javax.swing.JMenuItem mitTHONGKE;
    private javax.swing.JMenuItem mitTTPB;
    private javax.swing.JRadioButton rdbCT;
    private javax.swing.JRadioButton rdbDT;
    private javax.swing.JRadioButton rdbMDG;
    private javax.swing.JRadioButton rdbMPM;
    private javax.swing.JRadioButton rdbTT;
    private javax.swing.JTable tblPHIEUMUON;
    private javax.swing.JTextField txtMAPM;
    private javax.swing.JTextField txtPMMADOCGIA;
    private javax.swing.JTextField txtPMMANV;
    private javax.swing.JTextField txtPMNGAYMUON;
    private javax.swing.JTextField txtPMNGAYTRA;
    private javax.swing.JTextField txtSEACH;
    // End of variables declaration//GEN-END:variables

    private void themPM() {

        String mapm = null;
        int a;
        AD:
        for (int i = 1; i < 1000; i++) {
            a = i;
            String b = Integer.toString(a);
            if (b.length() == 1) {
                mapm = "PM00" + a;
            } else if (b.length() == 2) {
                mapm = "PM0" + a;
            } else if (b.length() > 2) {
                mapm = "PM" + a;
            } else {
            }
            boolean khIsExixst = false;
            for (Phieumuon pm : list) {
                if (pm.getMaphieumuon().equals(mapm)) {
                    khIsExixst = true;
                    break;
                }
            }
            if (!khIsExixst) {
                break;
            }
        }

        String madg = txtPMMADOCGIA.getText();
        String ngaym = txtPMNGAYMUON.getText();
        String ngayt = txtPMNGAYTRA.getText();
        int tt = 1;
        Phieumuon pm = new Phieumuon(mapm, madg, manv, ngaym, ngayt, tt);
        PhieumuonDao.themPhieumuon(pm);
        JOptionPane.showMessageDialog(this, "Thêm thành công");
    }

    private void xoaPhieumuon() {
        String mapm = txtMAPM.getText();
        PhieuphatDao.xoaPhieuphat(mapm);
        PhieumuonDao.xoaPhieumuon(mapm);
        JOptionPane.showMessageDialog(this, "Xóa phiếu mượn thành công");

    }

    private void capnhatPhieumuon() {
        String mapm = txtMAPM.getText();
        String madg = txtPMMADOCGIA.getText();
        String manv = txtPMMANV.getText();
        String ngaym = txtPMNGAYMUON.getText();
        String ngayt = txtPMNGAYTRA.getText();
        int tt = rdbDT.isSelected() ? 0 : 1;
        Phieumuon pm = new Phieumuon(mapm, madg, manv, ngaym, ngayt, tt);
        PhieumuonDao.capnhatPhieumuon(pm);
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");

    }

    private boolean kiemloiPM() {
        String madg = txtPMMADOCGIA.getText();
        String ngaym = txtPMNGAYMUON.getText();
        String ngayt = txtPMNGAYTRA.getText();
        if (madg.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã độc giả");
            return false;
        } else if (ngaym.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày mượn");
            return false;
        } else if (ngayt.equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày trả");
            return false;
        } else if (!rdbDT.isSelected() && !rdbCT.isSelected()) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn trạng thái");
            return false;
        } else {
//            SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
//            df.setLenient(false);
//            try {
//                df.parse(ngaym);
//                df.parse(ngayt);
//            } catch (ParseException e) {
//                JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày tháng năm đúng định dạng ngày/tháng/năm");
//                return false;
//            }
            Docgia listdg = null;
            try {
                List<Docgia> dg = DocgiaDao.laydulieuDocgia(" Where madg = '" + txtPMMADOCGIA.getText() + "'");
                if (!dg.isEmpty()) {
                    listdg = dg.get(0);
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmPHIEUMUON.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (listdg == null) {
                JOptionPane.showMessageDialog(this, "Mã độc giả không tồn tại");
                return false;
            }
        }
        return true;
    }

    private void timkiemPhieumuon() {
        String sql = "";
        if (rdbMPM.isSelected()) {
            sql = " WHERE maphieumuon = '" + txtSEACH.getText() + "'";
        } else if (rdbMDG.isSelected()) {
            sql = " WHERE madg = '" + txtSEACH.getText() + "'";
        } else if (rdbTT.isSelected()) {
            int tt = rdbDT.isSelected() ? 0 : 1;
            sql = " WHERE trangthai = " + tt;
        } else {
        }
        laydulieuPhieumuon(sql);
        laydulieuPM();
    }

}
